WebApplication2/Controllers/EtablishmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using Microsoft.AspNetCore.Http;
using AppContext = WebApplication2.Models.AppContext;

namespace WebApplication2.Controllers
{
    public class EtablishmentsController : Controller
    {
        private readonly AppContext _context;
        private const int admin_id = 1;

        public EtablishmentsController(AppContext context)
        {
            
            _context = context;
        }

        //TODO: Create index with the list of etablishment of the user
        // GET: Etablishments
        public async Task<IActionResult> Index()
        {
            var appContext = _context.etablishment.Include(e => e.etablishmentType).
                Where(s=> s.userEtablishment.userID == HttpContext.Session.GetInt32("userId"));
            return View(await appContext.ToListAsync());
        }

        //TODO: Create index with the list of etablishment of the user
        // GET: Etablishments
        public async Task<IActionResult> IndexAll()
        {
            var appContext = _context.etablishment.Include(e => e.etablishmentType).Where(s=> s.etablishmentID > 0);
            return View("index",await appContext.ToListAsync());
        }



        // GET: Etablishments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                
                return RedirectToAction("index", "home");
            }
            try
            {
                var etablishment = await _context.etablishment
               .Include(e => e.etablishmentType).Include(e => e.userEtablishment)
               .FirstOrDefaultAsync(m => m.etablishmentID == id);
                if (etablishment == null)
                {
                    
                    return RedirectToAction("index", "home");
                }
                try
                {
                    var t = _context.comment.Where(s => s.etablishmentID == id).ToList();
                  
                    ViewData["comment"] = t;
                }
                catch(Exception e)
                {
                    
                }
                
                return View(etablishment);
            }
            catch(Exception e)
            {
                
                return RedirectToAction("index", "home");
            }
           
        }

        // GET: Etablishments/Create
        public IActionResult Create()
        {
            
            ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type");
            return View();
        }

        // POST: Etablishments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("name,description,street,postalcode,phonenumber,email,etablishmenttypeID,img")] Etablishment etablishment)
        {
            if (ModelState.IsValid && HttpContext.Session.GetInt32("userId") != null)
            {  
                try
                {
                    _context.Add(etablishment);
                    _context.SaveChanges();
                    UserEtablishment u = new UserEtablishment();
                    u.etablishmentID = etablishment.etablishmentID;
                    u.userID = (int)HttpContext.Session.GetInt32("userId");
                    _context.Add(u);
                    _context.SaveChanges();
                    ViewData["msg"] = "salut";
                    return RedirectToAction("index","home");
                }
                catch(Exception e)
                {

                    return View("index", "home");
                    //TODO: add viewdata qui display un message d'erreur comme quoi y'a un problème
                }
            }
            ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type", etablishment.etablishmenttypeID);
            return View(etablishment);
        }

        // GET: Etablishments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "home");
            }

            try
            {
                var t = _context.etablishment.Where(s => s.userEtablishment.etablishmentID == id && s.userEtablishment.userID == HttpContext.Session.GetInt32("userId"))
                    .First();
                if (t == null)
                {
                    return RedirectToAction("index", "home");
                }
                ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type", t.etablishmenttypeID);
                return View(t);
            }
            catch(Exception)
            {
                return RedirectToAction("index", "home");
            }
            
            
        }

        // POST: Etablishments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("etablishmentID,name,description,street,postalcode,phonenumber,email,etablishmenttypeID,img")] Etablishment etablishment)
        {
            if (id != etablishment.etablishmentID)
            {
                return NotFound();
            }

            //TODO: quand les sessions seront up, il faut vérifier si l'utilisateur est bien propriétaire
            if (ModelState.IsValid)
            {
                try
                {
                    if(_context.etablishment.Any(s=> s.userEtablishment.etablishmentID == id && s.userEtablishment.userID == HttpContext.Session.GetInt32("userId")))
                    {
                        _context.Update(etablishment);
                        await _context.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EtablishmentExists(etablishment.etablishmentID))
                    {
                        return View("index", "home");
                    }
                    else
                    {
                        return View("index", "home");
                    }
                }
                return RedirectToAction();
            }
            ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type", etablishment.etablishmenttypeID);
            //done
            return View(etablishment);
        }

        // GET: Etablishments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var etablishment = await _context.etablishment
                .Include(e => e.etablishmentType)
                .Where(s => s.userEtablishment.userID == HttpContext.Session.GetInt32("userId") && s.userEtablishment.etablishmentID == id).FirstAsync();
                return View(etablishment);
            }
            catch(Exception )
            {
                return View("index", "home");
            }

            
        }

        // POST: Etablishments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var etablishment = await _context.etablishment.Where(e => e.userEtablishment.etablishmentID == id && e.userEtablishment.userID == HttpContext.Session.GetInt32("userId"))
                    .FirstAsync();
                if (etablishment == null)
                {
                    //failed
                    return RedirectToAction("index", "home");
                }
                _context.etablishment.Remove(etablishment);
                await _context.SaveChangesAsync();
                // done no error
                return RedirectToAction("index", "home");
            }
            catch(Exception)
            {
                //error
                return RedirectToAction("index", "home");
            }
        }

        private bool EtablishmentExists(int id)
        {
            return _context.etablishment.Any(e => e.etablishmentID == id);
        }
    }
}

WebApplication2/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using AppContext = WebApplication2.Models.AppContext;

namespace WebApplication2.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly AppContext _context;

        public ReservationsController(AppContext context)
        {
            _context = context;
        }

        // GET: Reservations
        public async Task<IActionResult> Index()
        {
            var appContext = _context.Reservation.Include(r => r.etablishment);
            return View(await appContext.ToListAsync());
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.etablishment)
                .FirstOrDefaultAsync(m => m.reservationID == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        
        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("arrive,depart,etablishmentID")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
               
                
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["etablishmentID"] = new SelectList(_context.etablishment, "etablishmentID", "description", reservation.etablishmentID);
            return View(reservation);
        }

        

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.etablishment)
                .FirstOrDefaultAsync(m => m.reservationID == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservation.FindAsync(id);
            _context.Reservation.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservation.Any(e => e.reservationID == id);
        }
    }
}

WebApplication2/Controllers/UserController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using AppContext = WebApplication2.Models.AppContext;
using System.Data;
using System.Text;

// User controler
namespace WebApplication2.Controllers
{
    public class UserController : Controller
    {

        private readonly AppContext _context;
        public UserController(AppContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public IActionResult UserLogin()
        {
            if (HttpContext.Session.GetInt32("userId") != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }


        public IActionResult UserLogout()
        {
            if (HttpContext.Session.GetInt32("userId") != null)
            {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult CheckUser(string username, string password)
        {
            
            var user = (from us in _context.user
                        where string.Compare(username, us.Login, StringComparison.OrdinalIgnoreCase) == 0
                        && string.Compare(Hash(password), us.Password, StringComparison.OrdinalIgnoreCase) == 0
                        select us).FirstOrDefault();

            if (user != null)
            {
                HttpContext.Session.SetInt32("userId", user.userID);
                HttpContext.Session.SetString("username", user.Login);

                return RedirectToAction("Success");
            }
            else
            {
                ViewBag.Error = true;
                return RedirectToAction("UserLogin");
            }


        }


        public ActionResult Success()
        {
            return View();

        }

        public ActionResult Disconnect()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult UserRegister()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateUser(string login, string password, string passwordRepeat)
        {
            
            
            if (login != null && password != null && passwordRepeat != null)
            {
                if (password == passwordRepeat)
                {
                    _context.user.Add(new Models.User {
                       Login = login,
                       Password = Hash(password),
                       accountTypeID = 1
                    });

                    _context.SaveChanges();

                    return RedirectToAction("Success");

                }
                else
                {
                    return RedirectToAction("UserRegister");
                }
            }
            else
            {
                return RedirectToAction("UserRegister");
            }
        }

        
        public ActionResult UserDetails()
        {
            var userId = HttpContext.Session.GetInt32("userId");
            var user = _context.user.Where(s => s.userID ==  HttpContext.Session.GetInt32("userId")).First();
            ViewData["details"] = user;
            return View();
        }

        [HttpPost]
        public ActionResult EditUser(string login, string password, string passwordRepeat)
        {
            
            if (password !=null){
                if (password == passwordRepeat)
                    {
                        var userId = HttpContext.Session.GetInt32("userId");
                        var pass = _context.user.First(a => a.userID == userId);
                        pass.Password = Hash(password);
                        _context.SaveChanges();
                        TempData["SuccessMessage"] = "Your success message here";
                        

                    }
            }
            return View("Success");
            


        }

        public string Hash(string password)
        {
            var bytes = new UTF8Encoding().GetBytes(password);
            var hashBytes = System.Security.Cryptography.MD5.Create().ComputeHash(bytes);
            return Convert.ToBase64String(hashBytes);
        }

    }
}

WebApplication2/Views/Shared/_Layout.cshtml
@{
    @using Microsoft.AspNetCore.Http;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-light navbar-fixed-top" style="background-color: #ff6d70;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">My holidays</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="float:right">

                    @if (Context.Session.GetString("username") != null)
                    {
                        <li><a asp-area="" asp-controller="User" asp-action="UserDetails">@Context.Session.GetString("username")</a></li>
                        <li><a asp-area="" asp-controller="User" asp-action="UserLogout">Logout</a></li>
                        <li><a asp-area="" asp-controller="Reservations" asp-action="Index">Mes réservations</a></li>
                        <li><a asp-area="" asp-controller="Etablishments" asp-action="Index">Listes hôtels</a></li>

                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="User" asp-action="UserLogin">Login</a></li>
                        <li><a asp-area="" asp-controller="User" asp-action="UserRegister">Register</a></li>
                    }

                </ul>
                <ul class="nav navbar-nav">

                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Etablishments" asp-action="IndexAll">Listes hôtels</a></li>

                </ul>
           </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebApplication2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>