WebApplication2/Models/Etablishment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Etablishment
    {
        public int etablishmentID { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string description { get; set; }
        [Required]
        public string street { get; set; }
        [Required]
        public string postalcode { get; set; }
        public string img { get; set; }
        public int nbChamber { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public int average { get; set; }
        public int etablishmenttypeID { get; set; }
        public virtual EtablishmentType etablishmentType { get; set; }
        public virtual UserEtablishment userEtablishment { get; set; }
        

       
    }
}

WebApplication2/Models/EtablishmentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class EtablishmentType
    {
        public int etablishmentTypeID { get; set; }
        public string type { get; set; }
    }
}

WebApplication2/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using Microsoft.AspNetCore.Http;
using AppContext = WebApplication2.Models.AppContext;

namespace WebApplication2.Controllers
{
    public class CommentsController : Controller
    {
        private readonly AppContext _context;

        public CommentsController(AppContext context)
        {
            _context = context;
        }

        

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("rating,comment,etablishmentID")] Comment pComment)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    pComment.userID = (int)HttpContext.Session.GetInt32("userId");
                    var t = _context.comment.Where(s => s.etablishmentID == pComment.etablishmentID && s.userID == (int)HttpContext.Session.GetInt32("userId")).FirstOrDefault();
                    if ( t != null)
                    {
                        t.rating = pComment.rating;
                        t.comment = pComment.comment;
                        _context.Update(t);
                    }
                    else
                    {
                        _context.Add(pComment);
                    }
                    await _context.SaveChangesAsync();
                    refreshRating(pComment.etablishmentID);
                    return RedirectToAction("Details", "Etablishments", new { id = pComment.etablishmentID });
                }
                catch(Exception e)
                {
                   
                    return RedirectToAction("Details", "Etablishments", new { id = pComment.etablishmentID });
                }
            }
            return RedirectToAction("Details", "Etablishments", new { id = pComment.etablishmentID });


        }
       

         
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed([Bind("etablishmentID")] Comment pComment)
        { 
            try
            {
                var comment = await _context.comment.Where(s => s.userID == HttpContext.Session.GetInt32("userId") && s.etablishmentID == pComment.etablishmentID).FirstAsync();
                _context.comment.Remove(comment);
                await _context.SaveChangesAsync();
                refreshRating(pComment.etablishmentID);
                return RedirectToAction("Details", "Etablishments", new { id = pComment.etablishmentID });
            }
            catch(Exception)
            {
                return RedirectToAction("Details", "Etablishments", new { id = pComment.etablishmentID });
            }
            
        }

        private bool CommentExists(int id)
        {
            return _context.comment.Any(e => e.etablishmentID == id);
        }

        public async void refreshRating(int etablishmentID)
        {
            var et = _context.etablishment.Where(s => s.etablishmentID == 1).First();
            var avg = _context.comment.Where(s => s.etablishmentID == 1);
            int i = 0;
            int compteur = 0;
            foreach (var t in avg)
            {
                i += t.rating;
                compteur++;
            }
            et.average = i / compteur;
            _context.etablishment.Update(et);
            _context.SaveChanges();
        }
            
    }
}

WebApplication2/Controllers/EtablishmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using Microsoft.AspNetCore.Http;
using AppContext = WebApplication2.Models.AppContext;

namespace WebApplication2.Controllers
{
    public class EtablishmentsController : Controller
    {
        private readonly AppContext _context;
        private const int admin_id = 1;

        public EtablishmentsController(AppContext context)
        {
            
            _context = context;
        }

        //TODO: Create index with the list of etablishment of the user
        // GET: Etablishments
        public async Task<IActionResult> Index()
        {
            var appContext = _context.etablishment.Include(e => e.etablishmentType).
                Where(s=> s.userEtablishment.userID == HttpContext.Session.GetInt32("userId"));
            return View(await appContext.ToListAsync());
        }

        //TODO: Create index with the list of etablishment of the user
        // GET: Etablishments
        public async Task<IActionResult> IndexAll()
        {
            var appContext = _context.etablishment.Include(e => e.etablishmentType).Where(s=> s.etablishmentID > 0);
            return View("index",await appContext.ToListAsync());
        }



        // GET: Etablishments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                
                return RedirectToAction("index", "home");
            }
            try
            {
                var etablishment = await _context.etablishment
               .Include(e => e.etablishmentType).Include(e => e.userEtablishment)
               .FirstOrDefaultAsync(m => m.etablishmentID == id);
                if (etablishment == null)
                {
                    
                    return RedirectToAction("index", "home");
                }
                try
                {
                    var t = _context.comment.Where(s => s.etablishmentID == id).ToList();
                  
                    ViewData["comment"] = t;
                }
                catch(Exception e)
                {
                    
                }
                
                return View(etablishment);
            }
            catch(Exception e)
            {
                
                return RedirectToAction("index", "home");
            }
           
        }

        // GET: Etablishments/Create
        public IActionResult Create()
        {
            
            ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type");
            return View();
        }

        // POST: Etablishments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("name,description,street,postalcode,phonenumber,email,etablishmenttypeID,img")] Etablishment etablishment)
        {
            if (ModelState.IsValid && HttpContext.Session.GetInt32("userId") != null)
            {  
                try
                {
                    _context.Add(etablishment);
                    _context.SaveChanges();
                    UserEtablishment u = new UserEtablishment();
                    u.etablishmentID = etablishment.etablishmentID;
                    u.userID = (int)HttpContext.Session.GetInt32("userId");
                    _context.Add(u);
                    _context.SaveChanges();
                    ViewData["msg"] = "salut";
                    return RedirectToAction("index","home");
                }
                catch(Exception e)
                {

                    return View("index", "home");
                    //TODO: add viewdata qui display un message d'erreur comme quoi y'a un problème
                }
            }
            ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type", etablishment.etablishmenttypeID);
            return View(etablishment);
        }

        // GET: Etablishments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "home");
            }

            try
            {
                var t = _context.etablishment.Where(s => s.userEtablishment.etablishmentID == id && s.userEtablishment.userID == HttpContext.Session.GetInt32("userId"))
                    .First();
                if (t == null)
                {
                    return RedirectToAction("index", "home");
                }
                ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type", t.etablishmenttypeID);
                return View(t);
            }
            catch(Exception)
            {
                return RedirectToAction("index", "home");
            }
            
            
        }

        // POST: Etablishments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("etablishmentID,name,description,street,postalcode,phonenumber,email,etablishmenttypeID,img")] Etablishment etablishment)
        {
            if (id != etablishment.etablishmentID)
            {
                return NotFound();
            }

            //TODO: quand les sessions seront up, il faut vérifier si l'utilisateur est bien propriétaire
            if (ModelState.IsValid)
            {
                try
                {
                    if(_context.etablishment.Any(s=> s.userEtablishment.etablishmentID == id && s.userEtablishment.userID == HttpContext.Session.GetInt32("userId")))
                    {
                        _context.Update(etablishment);
                        await _context.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EtablishmentExists(etablishment.etablishmentID))
                    {
                        return View("index", "home");
                    }
                    else
                    {
                        return View("index", "home");
                    }
                }
                return RedirectToAction();
            }
            ViewData["etablishmenttypeID"] = new SelectList(_context.etablishmentType, "etablishmentTypeID", "type", etablishment.etablishmenttypeID);
            //done
            return View(etablishment);
        }

        // GET: Etablishments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var etablishment = await _context.etablishment
                .Include(e => e.etablishmentType)
                .Where(s => s.userEtablishment.userID == HttpContext.Session.GetInt32("userId") && s.userEtablishment.etablishmentID == id).FirstAsync();
                return View(etablishment);
            }
            catch(Exception )
            {
                return View("index", "home");
            }

            
        }

        // POST: Etablishments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var etablishment = await _context.etablishment.Where(e => e.userEtablishment.etablishmentID == id && e.userEtablishment.userID == HttpContext.Session.GetInt32("userId"))
                    .FirstAsync();
                if (etablishment == null)
                {
                    //failed
                    return RedirectToAction("index", "home");
                }
                _context.etablishment.Remove(etablishment);
                await _context.SaveChangesAsync();
                // done no error
                return RedirectToAction("index", "home");
            }
            catch(Exception)
            {
                //error
                return RedirectToAction("index", "home");
            }
        }

        private bool EtablishmentExists(int id)
        {
            return _context.etablishment.Any(e => e.etablishmentID == id);
        }
    }
}

WebApplication2/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using AppContext = WebApplication2.Models.AppContext;

namespace WebApplication2.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly AppContext _context;

        public ReservationsController(AppContext context)
        {
            _context = context;
        }

        // GET: Reservations
        public async Task<IActionResult> Index()
        {
            var appContext = _context.Reservation.Include(r => r.etablishment);
            return View(await appContext.ToListAsync());
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.etablishment)
                .FirstOrDefaultAsync(m => m.reservationID == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        
        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("arrive,depart,etablishmentID")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
               
                
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["etablishmentID"] = new SelectList(_context.etablishment, "etablishmentID", "description", reservation.etablishmentID);
            return View(reservation);
        }

        

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.etablishment)
                .FirstOrDefaultAsync(m => m.reservationID == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservation.FindAsync(id);
            _context.Reservation.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservation.Any(e => e.reservationID == id);
        }
    }
}

WebApplication2/Views/Etablishments/Create.cshtml
@model WebApplication2.Models.Etablishment

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Etablishment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select name="img">
                    <option value="image1.svg">image 1</option>
                    <option value="image2.svg">image 2</option>
                    <option value="image3.svg">image 3</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="street" class="control-label"></label>
                <input asp-for="street" class="form-control" />
                <span asp-validation-for="street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="postalcode" class="control-label"></label>
                <input asp-for="postalcode" class="form-control" />
                <span asp-validation-for="postalcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phonenumber" class="control-label"></label>
                <input asp-for="phonenumber" class="form-control" />
                <span asp-validation-for="phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="etablishmenttypeID" class="control-label">Type : </label>
                <select asp-for="etablishmenttypeID" class="form-control" asp-items="ViewBag.etablishmenttypeID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Etablishments/Delete.cshtml
@model WebApplication2.Models.Etablishment

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Etablishment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.postalcode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.postalcode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.phonenumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.phonenumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.average)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.average)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.etablishmentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.etablishmentType.etablishmentTypeID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="etablishmentID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication2/Views/Etablishments/Details.cshtml
@model WebApplication2.Models.Etablishment
@using Microsoft.AspNetCore.Http;
@{


    ViewData["Title"] = "Details";
    var test = (List<Comment>)ViewData["comment"];
    Comment toto = null;
    var isConnected = false;
    int userID = -1;
    try
    {
        toto = test.Find(x => x.userID == Context.Session.GetInt32("userId"));
        test.Remove(toto);

        
        if (Context.Session.GetInt32("userId") != null)
        {

            userID = (int)Context.Session.GetInt32("userId");
            isConnected = true;
        }

    }
    catch (Exception)
    {

    }


}

<h2>Details</h2>

<div>
    <h4>Etablishment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.postalcode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.postalcode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.phonenumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.phonenumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.average)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.average)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.etablishmentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.etablishmentType.etablishmentTypeID)
        </dd>
    </dl>
</div>

@if (isConnected)
{
<form method="POST" asp-antiforgery="true" action="@Url.Action("Create", "Comments")">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">

        <input name="rating" class="form-control" />

    </div>
    <div class="form-group">
        <input value="comment" name="comment" class="form-control" />

    </div>
    <div class="form-group">
        <input name="etablishmentID" value="@Model.etablishmentID" type="hidden" />
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</form>
<form method="POST" asp-antiforgery="true" action="@Url.Action("Create","Reservations")">

    <div class="form-group">
       
        <input name="arrive" class="form-control" />
        
    </div>
    <div class="form-group">
        
        <input name="depart" class="form-control" />
      
    </div>
    <div class="form-group">
        <input name="etablishmentID" type="hidden" value="@Model.etablishmentID" />
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
</form>
}
<div>
    <!-- if user is not the owner of the etablishment, do not display edit and back to list-->

    @{
        
        try
        {

            if (isConnected && userID == Model.userEtablishment.userID)
            {
                
                
                <a asp-action="Edit" asp-route-id="@Model.etablishmentID">Edit</a>
                <a asp-action="Index">Back to List</a>
            }
        }
        catch (Exception)
        {

        }

    }
    @if (toto != null)
    {
        <p>Mon commentaire</p>
        @toto.comment
        @toto.rating

        <form asp-antiforgery="true" action="@Url.Action("Delete","Comments")/@toto.userID" method="post">
            <input type="hidden" name="etablishmentID" value="@toto.etablishmentID" />
            <input type="submit" value="Delete" class="btn btn-default" />
        </form>
    }
    <br />
    <br />
    <br />
    <br />
    @for (var i = 0; i < test.Count; i++)
        {
        <br />
        <p>Commentaire autre utilisateurs</p>
        @test[i].comment
        @test[i].rating
        }
    



</div>

WebApplication2/Views/Etablishments/Edit.cshtml
@model WebApplication2.Models.Etablishment

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Etablishment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="etablishmentID" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="street" class="control-label"></label>
                <input asp-for="street" class="form-control" />
                <span asp-validation-for="street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="postalcode" class="control-label"></label>
                <input asp-for="postalcode" class="form-control" />
                <span asp-validation-for="postalcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select name="img">
                    <option value="image1.svg">image 1</option>
                    <option value="image2.svg">image 2</option>
                    <option value="image3.svg">image 3</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="phonenumber" class="control-label"></label>
                <input asp-for="phonenumber" class="form-control" />
                <span asp-validation-for="phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="etablishmenttypeID" class="control-label"></label>
                <select asp-for="etablishmenttypeID" class="form-control" asp-items="ViewBag.etablishmenttypeID"></select>
                <span asp-validation-for="etablishmenttypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Etablishments/Index.cshtml
@model IEnumerable<WebApplication2.Models.Etablishment>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.postalcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phonenumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.average)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.etablishmentType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.postalcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phonenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.average)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.etablishmentType.etablishmentTypeID)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.etablishmentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.etablishmentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.etablishmentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>